
// Objeto con categorías de estudio
const categories = {
    words: [
        { "word": "the", "translation": "el / la / los / las" },
        { "word": "be", "translation": "ser / estar" },
        { "word": "to", "translation": "a / para" },
        { "word": "of", "translation": "de" },
        { "word": "and", "translation": "y" },
        { "word": "a", "translation": "un / una" },
        { "word": "in", "translation": "en / dentro" },
        { "word": "that", "translation": "ese / esa / que" },
        { "word": "have", "translation": "tener" },
        { "word": "I", "translation": "yo" },
        { "word": "it", "translation": "eso / lo / la" },
        { "word": "for", "translation": "para / por" },
        { "word": "not", "translation": "no" },
        { "word": "on", "translation": "en / sobre" },
        { "word": "with", "translation": "con" },
        { "word": "he", "translation": "él" },
        { "word": "as", "translation": "como" },
        { "word": "you", "translation": "tú / usted" },
        { "word": "do", "translation": "hacer" },
        { "word": "at", "translation": "en / a" },
        { "word": "this", "translation": "este / esta" },
        { "word": "but", "translation": "pero" },
        { "word": "his", "translation": "su (de él)" },
        { "word": "by", "translation": "por / cerca de" },
        { "word": "from", "translation": "de / desde" },
        { "word": "they", "translation": "ellos / ellas" },
        { "word": "we", "translation": "nosotros" },
        { "word": "say", "translation": "decir" },
        { "word": "her", "translation": "su / de ella" },
        { "word": "she", "translation": "ella" },
        { "word": "or", "translation": "o" },
        { "word": "an", "translation": "un / una" },
        { "word": "will", "translation": "auxiliar futuro (hará)" },
        { "word": "my", "translation": "mi" },
        { "word": "one", "translation": "uno" },
        { "word": "all", "translation": "todo / todos" },
        { "word": "would", "translation": "haría / sería" },
        { "word": "there", "translation": "ahí / allí" },
        { "word": "their", "translation": "su / de ellos" },
        { "word": "what", "translation": "qué" },
        { "word": "so", "translation": "tan / así / entonces" },
        { "word": "up", "translation": "arriba" },
        { "word": "out", "translation": "afuera / salir" },
        { "word": "if", "translation": "si" },
        { "word": "about", "translation": "sobre / acerca de" },
        { "word": "who", "translation": "quién" },
        { "word": "get", "translation": "obtener / conseguir" },
        { "word": "which", "translation": "cuál / que" },
        { "word": "go", "translation": "ir" },
        { "word": "me", "translation": "me / a mí" },
        { "word": "when", "translation": "cuando" },
        { "word": "make", "translation": "hacer / crear" },
        { "word": "can", "translation": "poder" },
        { "word": "like", "translation": "gustar / como" },
        { "word": "time", "translation": "tiempo" },
        { "word": "no", "translation": "no" },
        { "word": "just", "translation": "solo / justo" },
        { "word": "him", "translation": "lo / a él" },
        { "word": "know", "translation": "saber / conocer" },
        { "word": "take", "translation": "tomar / llevar" },
        { "word": "people", "translation": "gente" },
        { "word": "into", "translation": "dentro de / en" },
        { "word": "year", "translation": "año" },
        { "word": "your", "translation": "tu / su" },
        { "word": "good", "translation": "bueno" },
        { "word": "some", "translation": "algunos / algo de" },
        { "word": "could", "translation": "podría" },
        { "word": "them", "translation": "ellos / las / los" },
        { "word": "see", "translation": "ver" },
        { "word": "other", "translation": "otro" },
        { "word": "than", "translation": "que / en lugar de" },
        { "word": "then", "translation": "entonces / luego" },
        { "word": "now", "translation": "ahora" },
        { "word": "look", "translation": "mirar" },
        { "word": "only", "translation": "solo / únicamente" },
        { "word": "come", "translation": "venir" },
        { "word": "its", "translation": "su (de eso)" },
        { "word": "over", "translation": "sobre / encima" },
        { "word": "think", "translation": "pensar" },
        { "word": "also", "translation": "también" },
        { "word": "back", "translation": "espalda / atrás / de vuelta" },
        { "word": "after", "translation": "después" },
        { "word": "use", "translation": "usar" },
        { "word": "two", "translation": "dos" },
        { "word": "how", "translation": "cómo" },
        { "word": "our", "translation": "nuestro" },
        { "word": "work", "translation": "trabajo / trabajar" },
        { "word": "first", "translation": "primero" },
        { "word": "well", "translation": "bien" },
        { "word": "way", "translation": "camino / manera" },
        { "word": "even", "translation": "incluso / aún" },
        { "word": "new", "translation": "nuevo" },
        { "word": "want", "translation": "querer" },
        { "word": "because", "translation": "porque" },
        { "word": "any", "translation": "cualquier / alguno" },
        { "word": "these", "translation": "estos / estas" },
        { "word": "give", "translation": "dar" },
        { "word": "day", "translation": "día" },
        { "word": "most", "translation": "la mayoría / más" },
        { "word": "us", "translation": "nosotros / nos" },
        { "word": "very", "translation": "muy" },
        { "word": "her", "translation": "ella / su" },
        { "word": "make", "translation": "hacer" },
        { "word": "thing", "translation": "cosa" },
        { "word": "see", "translation": "ver" },
        { "word": "himself", "translation": "él mismo" },
        { "word": "long", "translation": "largo" },
        { "word": "great", "translation": "gran / genial" },
        { "word": "still", "translation": "todavía / aún" },
        { "word": "own", "translation": "propio" },
        { "word": "too", "translation": "también / demasiado" },
        { "word": "last", "translation": "último / durar" },
        { "word": "might", "translation": "podría" },
        { "word": "must", "translation": "deber / tener que" },
        { "word": "little", "translation": "pequeño / poco" },
        { "word": "house", "translation": "casa" },
        { "word": "man", "translation": "hombre" },
        { "word": "place", "translation": "lugar" },
        { "word": "between", "translation": "entre" },
        { "word": "while", "translation": "mientras / rato" },
        { "word": "under", "translation": "debajo" },
        { "word": "found", "translation": "encontró" },
        { "word": "those", "translation": "esos / esas" },
        { "word": "never", "translation": "nunca" },
        { "word": "each", "translation": "cada" },
        { "word": "during", "translation": "durante" },
        { "word": "always", "translation": "siempre" },
        { "word": "without", "translation": "sin" },
        { "word": "again", "translation": "otra vez" },
        { "word": "around", "translation": "alrededor" },
        { "word": "small", "translation": "pequeño" },
        { "word": "another", "translation": "otro / otra" },
        { "word": "however", "translation": "sin embargo" },
        { "word": "family", "translation": "familia" },
        { "word": "world", "translation": "mundo" },
        { "word": "number", "translation": "número" },
        { "word": "often", "translation": "a menudo" },
        { "word": "hand", "translation": "mano" },
        { "word": "old", "translation": "viejo" },
        { "word": "life", "translation": "vida" },
        { "word": "tell", "translation": "decir / contar" },
        { "word": "write", "translation": "escribir" },
        { "word": "become", "translation": "convertirse en" },
        { "word": "show", "translation": "mostrar" },
        { "word": "part", "translation": "parte" },
        { "word": "about", "translation": "acerca de / sobre" },
        { "word": "against", "translation": "contra" },
        { "word": "place", "translation": "lugar" },
        { "word": "over", "translation": "sobre / encima" },
        { "word": "such", "translation": "tal / semejante" },
        { "word": "again", "translation": "otra vez" },
        { "word": "case", "translation": "caso" },
        { "word": "most", "translation": "la mayoría / más" },
        { "word": "week", "translation": "semana" },
        { "word": "company", "translation": "compañía / empresa" },
        { "word": "where", "translation": "dónde" },
        { "word": "system", "translation": "sistema" },
        { "word": "each", "translation": "cada" },
        { "word": "right", "translation": "derecho / correcto" },
        { "word": "program", "translation": "programa" },
        { "word": "hear", "translation": "oír" },
        { "word": "question", "translation": "pregunta" },
        { "word": "work", "translation": "trabajar / trabajo" },
        { "word": "play", "translation": "jugar / tocar (instrumento)" },
        { "word": "government", "translation": "gobierno" },
        { "word": "run", "translation": "correr / dirigir" },
        { "word": "small", "translation": "pequeño" },
        { "word": "number", "translation": "número" },
        { "word": "off", "translation": "apagado / fuera de" },
        { "word": "always", "translation": "siempre" },
        { "word": "move", "translation": "mover / mudarse" },
        { "word": "like", "translation": "gustar / como" },
        { "word": "night", "translation": "noche" },
        { "word": "live", "translation": "vivir" },
        { "word": "Mr.", "translation": "Sr." },
        { "word": "point", "translation": "punto" },
        { "word": "believe", "translation": "creer" },
        { "word": "hold", "translation": "sostener" },
        { "word": "today", "translation": "hoy" },
        { "word": "bring", "translation": "traer" },
        { "word": "happen", "translation": "suceder" },
        { "word": "next", "translation": "siguiente / próximo" },
        { "word": "without", "translation": "sin" },
        { "word": "before", "translation": "antes" },
        { "word": "large", "translation": "grande" },
        { "word": "all", "translation": "todo / todos" },
        { "word": "million", "translation": "millón" },
        { "word": "must", "translation": "deber" },
        { "word": "home", "translation": "hogar / casa" },
        { "word": "understand", "translation": "entender" },
        { "word": "room", "translation": "habitación / cuarto" },
        { "word": "area", "translation": "área / zona" },
        { "word": "money", "translation": "dinero" },
        { "word": "story", "translation": "historia / cuento" },
        { "word": "young", "translation": "joven" },
        { "word": "fact", "translation": "hecho" },
        { "word": "month", "translation": "mes" },
        { "word": "different", "translation": "diferente" },
        { "word": "lot", "translation": "mucho / un montón" },
        { "word": "study", "translation": "estudiar" },
        { "word": "book", "translation": "libro" },
        { "word": "eye", "translation": "ojo" },
        { "word": "job", "translation": "trabajo / empleo" },
        { "word": "word", "translation": "palabra" },
        { "word": "though", "translation": "aunque" },
        { "word": "business", "translation": "negocio / empresa" },
        { "word": "issue", "translation": "tema / problema" },
        { "word": "side", "translation": "lado" },
        { "word": "kind", "translation": "tipo / amable" },
        { "word": "four", "translation": "cuatro" },
        { "word": "head", "translation": "cabeza / dirigir" },
        { "word": "far", "translation": "lejos" },
        { "word": "black", "translation": "negro" },
        { "word": "long", "translation": "largo" },
        { "word": "both", "translation": "ambos" },
        { "word": "little", "translation": "pequeño / poco" },
        { "word": "house", "translation": "casa" },
        { "word": "yes", "translation": "sí" },
        { "word": "after", "translation": "después" },
        { "word": "since", "translation": "desde / ya que" },
        { "word": "long", "translation": "largo" },
        { "word": "provide", "translation": "proveer / proporcionar" },
        { "word": "service", "translation": "servicio" },
        { "word": "around", "translation": "alrededor" },
        { "word": "friend", "translation": "amigo" },
        { "word": "important", "translation": "importante" },
        { "word": "father", "translation": "padre" },
        { "word": "sit", "translation": "sentarse" },
        { "word": "away", "translation": "lejos / fuera" },
        { "word": "until", "translation": "hasta" },
        { "word": "power", "translation": "poder / energía" },
        { "word": "hour", "translation": "hora" },
        { "word": "game", "translation": "juego" },
        { "word": "often", "translation": "a menudo" },
        { "word": "yet", "translation": "todavía / aún" },
        { "word": "line", "translation": "línea / fila" },
        { "word": "political", "translation": "político" },
        { "word": "end", "translation": "fin / terminar" },
        { "word": "among", "translation": "entre" },
        { "word": "ever", "translation": "alguna vez / siempre" },
        { "word": "stand", "translation": "estar de pie / soportar" },
        { "word": "bad", "translation": "malo" },
        { "word": "lose", "translation": "perder" },
        { "word": "however", "translation": "sin embargo" },
        { "word": "member", "translation": "miembro" },
        { "word": "pay", "translation": "pagar" },
        { "word": "law", "translation": "ley" },
        { "word": "meet", "translation": "encontrar / reunirse" },
        { "word": "car", "translation": "coche / carro" },
        { "word": "city", "translation": "ciudad" },
        { "word": "almost", "translation": "casi" },
        { "word": "include", "translation": "incluir" },
        { "word": "continue", "translation": "continuar" },
        { "word": "set", "translation": "colocar / conjunto" },
        { "word": "later", "translation": "más tarde" },
        { "word": "community", "translation": "comunidad" },
        { "word": "much", "translation": "mucho" },
        { "word": "name", "translation": "nombre" },
        { "word": "five", "translation": "cinco" },
        { "word": "once", "translation": "una vez / en cuanto" },
        { "word": "white", "translation": "blanco" },
        { "word": "least", "translation": "menos / al menos" },
        { "word": "president", "translation": "presidente" },
        { "word": "learn", "translation": "aprender" },
        { "word": "real", "translation": "real / verdadero" },
        { "word": "change", "translation": "cambiar / cambio" },
        { "word": "team", "translation": "equipo" },
        { "word": "minute", "translation": "minuto" },
        { "word": "best", "translation": "mejor" },
        { "word": "several", "translation": "varios" },
        { "word": "idea", "translation": "idea" },
        { "word": "kid", "translation": "niño" },
        { "word": "body", "translation": "cuerpo" },
        { "word": "information", "translation": "información" },
        { "word": "nothing", "translation": "nada" },
        { "word": "ago", "translation": "hace (tiempo)" },
        { "word": "lead", "translation": "liderar / dirigir" },
        { "word": "social", "translation": "social" },
        { "word": "understand", "translation": "entender" },
        { "word": "whether", "translation": "si (condicional)" },
        { "word": "watch", "translation": "mirar / reloj" },
        { "word": "together", "translation": "juntos" },
        { "word": "follow", "translation": "seguir" },
        { "word": "around", "translation": "alrededor" },
        { "word": "parent", "translation": "padre / madre" },
        { "word": "only", "translation": "solo / solamente" },
        { "word": "stop", "translation": "detener / parar" },
        { "word": "face", "translation": "cara / enfrentar" },
        { "word": "anything", "translation": "cualquier cosa" },
        { "word": "create", "translation": "crear" },
        { "word": "public", "translation": "público" },
        { "word": "already", "translation": "ya" },
        { "word": "speak", "translation": "hablar" },
        { "word": "others", "translation": "otros" },
        { "word": "read", "translation": "leer" },
        { "word": "allow", "translation": "permitir" },
        { "word": "add", "translation": "añadir" },
        { "word": "office", "translation": "oficina" },
        { "word": "spend", "translation": "gastar / pasar (tiempo)" },
        { "word": "door", "translation": "puerta" },
        { "word": "health", "translation": "salud" },
        { "word": "person", "translation": "persona" },
        { "word": "art", "translation": "arte" },
        { "word": "sure", "translation": "seguro" },
        { "word": "such", "translation": "tal / semejante" },
        { "word": "war", "translation": "guerra" },
        { "word": "history", "translation": "historia" },
        { "word": "party", "translation": "fiesta / partido" },
        { "word": "within", "translation": "dentro de" },
        { "word": "grow", "translation": "crecer" },
        { "word": "result", "translation": "resultado" },
        { "word": "open", "translation": "abrir / abierto" },
        { "word": "change", "translation": "cambiar / cambio" },
        { "word": "morning", "translation": "mañana" },
        { "word": "walk", "translation": "caminar / paseo" },
        { "word": "reason", "translation": "razón / motivo" },
        { "word": "low", "translation": "bajo" },
        { "word": "win", "translation": "ganar" },
        { "word": "research", "translation": "investigación" },
        { "word": "girl", "translation": "chica / niña" },
        { "word": "guy", "translation": "chico / tipo" },
        { "word": "early", "translation": "temprano" },
        { "word": "food", "translation": "comida" },
        { "word": "before", "translation": "antes" },
        { "word": "moment", "translation": "momento" },
        { "word": "himself", "translation": "él mismo" },
        { "word": "air", "translation": "aire" },
        { "word": "teacher", "translation": "profesor" },
        { "word": "force", "translation": "fuerza / obligar" },
        { "word": "offer", "translation": "oferta / ofrecer" },
        { "word": "enough", "translation": "suficiente" },
        { "word": "both", "translation": "ambos" },
        { "word": "education", "translation": "educación" },
        { "word": "across", "translation": "a través de / al otro lado" },
        { "word": "although", "translation": "aunque" },
        { "word": "remember", "translation": "recordar" },
        { "word": "foot", "translation": "pie" },
        { "word": "second", "translation": "segundo" },
        { "word": "boy", "translation": "niño" },
        { "word": "maybe", "translation": "quizás" },
        { "word": "toward", "translation": "hacia" },
        { "word": "able", "translation": "capaz" },
        { "word": "age", "translation": "edad" },
        { "word": "off", "translation": "apagado / fuera de" },
        { "word": "policy", "translation": "política / norma" },
        { "word": "everything", "translation": "todo" },
        { "word": "love", "translation": "amor / amar" },
        { "word": "process", "translation": "proceso" },
        { "word": "music", "translation": "música" },
        { "word": "including", "translation": "incluyendo" },
        { "word": "consider", "translation": "considerar" },
        { "word": "appear", "translation": "aparecer" },
        { "word": "actually", "translation": "en realidad" },
        { "word": "buy", "translation": "comprar" },
        { "word": "probably", "translation": "probablemente" },
        { "word": "human", "translation": "humano" },
        { "word": "wait", "translation": "esperar" },
        { "word": "serve", "translation": "servir" },
        { "word": "market", "translation": "mercado" },
        { "word": "die", "translation": "morir" },
        { "word": "send", "translation": "enviar" },
        { "word": "expect", "translation": "esperar (algo)" },
        { "word": "sense", "translation": "sentido" },
        { "word": "build", "translation": "construir" },
        { "word": "stay", "translation": "quedarse" },
        { "word": "fall", "translation": "caer / otoño" },
        { "word": "oh", "translation": "oh" },
        { "word": "nation", "translation": "nación" },
        { "word": "plan", "translation": "plan / planear" },
        { "word": "cut", "translation": "cortar" },
        { "word": "college", "translation": "universidad" },
        { "word": "interest", "translation": "interés" },
        { "word": "death", "translation": "muerte" },
        { "word": "course", "translation": "curso" },
        { "word": "someone", "translation": "alguien" },
        { "word": "experience", "translation": "experiencia" },
        { "word": "behind", "translation": "detrás" },
        { "word": "reach", "translation": "alcanzar / llegar" },
        { "word": "local", "translation": "local" },
        { "word": "kill", "translation": "matar" },
        { "word": "six", "translation": "seis" },
        { "word": "remain", "translation": "permanecer" },
        { "word": "effect", "translation": "efecto" },
        { "word": "yeah", "translation": "sí" },
        { "word": "suggest", "translation": "sugerir" },
        { "word": "class", "translation": "clase" },
        { "word": "control", "translation": "control / controlar" },
        { "word": "raise", "translation": "levantar / aumentar" },
        { "word": "care", "translation": "cuidar / cuidado" },
        { "word": "perhaps", "translation": "quizás" },
        { "word": "late", "translation": "tarde" },
        { "word": "hard", "translation": "difícil / duro" },
        { "word": "field", "translation": "campo" },
        { "word": "else", "translation": "más / otro" },
        { "word": "pass", "translation": "pasar" },
        { "word": "former", "translation": "anterior" },
        { "word": "sell", "translation": "vender" },
        { "word": "major", "translation": "principal / importante" },
        { "word": "sometimes", "translation": "a veces" },
        { "word": "require", "translation": "requerir" },
        { "word": "along", "translation": "a lo largo / junto" },
        { "word": "close", "translation": "cerrar" },
        { "word": "hard", "translation": "duro" },
        { "word": "open", "translation": "abrir" },
        { "word": "example", "translation": "ejemplo" },
        { "word": "begin", "translation": "empezar" },
        { "word": "life", "translation": "vida" },
        { "word": "always", "translation": "siempre" },
        { "word": "those", "translation": "aquellos" },
        { "word": "both", "translation": "ambos" },
        { "word": "paper", "translation": "papel" },
        { "word": "together", "translation": "juntos" },
        { "word": "got", "translation": "obtuvo" },
        { "word": "group", "translation": "grupo" },
        { "word": "often", "translation": "a menudo" },
        { "word": "run", "translation": "correr" },
        { "word": "important", "translation": "importante" },
        { "word": "until", "translation": "hasta" },
        { "word": "children", "translation": "niños" },
        { "word": "side", "translation": "lado" },
        { "word": "feet", "translation": "pies" },
        { "word": "car", "translation": "carro" },
        { "word": "mile", "translation": "milla" },
        { "word": "night", "translation": "noche" },
        { "word": "walk", "translation": "caminar" },
        { "word": "white", "translation": "blanco" },
        { "word": "sea", "translation": "mar" },
        { "word": "began", "translation": "comenzó" },
        { "word": "grow", "translation": "crecer" },
        { "word": "took", "translation": "tomó" },
        { "word": "river", "translation": "río" },
        { "word": "four", "translation": "cuatro" },
        { "word": "carry", "translation": "cargar" },
        { "word": "state", "translation": "estado" },
        { "word": "once", "translation": "una vez" },
        { "word": "book", "translation": "libro" },
        { "word": "hear", "translation": "oír" },
        { "word": "stop", "translation": "detener" },
        { "word": "without", "translation": "sin" },
        { "word": "second", "translation": "segundo" },
        { "word": "later", "translation": "más tarde" },
        { "word": "miss", "translation": "extrañar / perder" },
        { "word": "idea", "translation": "idea" },
        { "word": "enough", "translation": "suficiente" },
        { "word": "eat", "translation": "comer" },
        { "word": "face", "translation": "cara" },
        { "word": "watch", "translation": "mirar / reloj" },
        { "word": "far", "translation": "lejos" },
        { "word": "Indian", "translation": "indio" },
        { "word": "real", "translation": "real" },
        { "word": "almost", "translation": "casi" },
        { "word": "let", "translation": "permitir / dejar" },
        { "word": "above", "translation": "encima" },
        { "word": "girl", "translation": "niña" },
        { "word": "sometimes", "translation": "a veces" },
        { "word": "mountain", "translation": "montaña" },
        { "word": "cut", "translation": "cortar" },
        { "word": "young", "translation": "joven" },
        { "word": "talk", "translation": "hablar" },
        { "word": "soon", "translation": "pronto" },
        { "word": "list", "translation": "lista" },
        { "word": "song", "translation": "canción" },
        { "word": "being", "translation": "ser / estando" },
        { "word": "leave", "translation": "dejar / irse" },
        { "word": "family", "translation": "familia" },
        { "word": "it's", "translation": "es / está" },
        { "word": "body", "translation": "cuerpo" },
        { "word": "music", "translation": "música" },
        { "word": "color", "translation": "color" },
        { "word": "stand", "translation": "pararse" },
        { "word": "sun", "translation": "sol" },
        { "word": "questions", "translation": "preguntas" },
        { "word": "fish", "translation": "pez" },
        { "word": "area", "translation": "área" },
        { "word": "mark", "translation": "marca" },
        { "word": "dog", "translation": "perro" },
        { "word": "horse", "translation": "caballo" },
        { "word": "birds", "translation": "pájaros" },
        { "word": "problem", "translation": "problema" },
        { "word": "complete", "translation": "completar" },
        { "word": "room", "translation": "habitación" },
        { "word": "knew", "translation": "sabía" },
        { "word": "since", "translation": "desde" },
        { "word": "ever", "translation": "alguna vez" },
        { "word": "piece", "translation": "pieza" },
        { "word": "told", "translation": "dijo" },
        { "word": "usually", "translation": "usualmente" },
        { "word": "didn't", "translation": "no hizo" },
        { "word": "friends", "translation": "amigos" },
        { "word": "easy", "translation": "fácil" },
        { "word": "heard", "translation": "escuchó" },
        { "word": "order", "translation": "orden" },
        { "word": "red", "translation": "rojo" },
        { "word": "door", "translation": "puerta" },
        { "word": "sure", "translation": "seguro" },
        { "word": "become", "translation": "convertirse" },
        { "word": "top", "translation": "arriba / cima" },
        { "word": "ship", "translation": "barco" },
        { "word": "across", "translation": "a través" },
        { "word": "today", "translation": "hoy" },
        { "word": "during", "translation": "durante" },
        { "word": "short", "translation": "corto" },
        { "word": "better", "translation": "mejor" },
        { "word": "best", "translation": "el mejor" },
        { "word": "however", "translation": "sin embargo" },
        { "word": "low", "translation": "bajo" }
    ],
    greetings: [
        { word: "Hello", translation: "Hola" },
        { word: "Hi", translation: "Hola" },
        { word: "Hey", translation: "Oye/Hola informal" },
        { word: "Good morning", translation: "Buenos días" },
        { word: "Good afternoon", translation: "Buenas tardes" },
        { word: "Good evening", translation: "Buenas noches (saludo)" },
        { word: "Good night", translation: "Buenas noches (despedida)" },
        { word: "See you later", translation: "Hasta luego" },
        { word: "See you soon", translation: "Nos vemos pronto" },
        { word: "See you tomorrow", translation: "Nos vemos mañana" },
        { word: "See you next time", translation: "Hasta la próxima" },
        { word: "See you around", translation: "Nos vemos por ahí" },
        { word: "Take care", translation: "Cuídate" },
        { word: "Have a nice day", translation: "Que tengas un buen día" },
        { word: "Have a good one", translation: "Que te vaya bien" },
        { word: "Have a great weekend", translation: "Que tengas un gran fin de semana" },
        { word: "Have fun", translation: "Diviértete" },
        { word: "Welcome", translation: "Bienvenido/a" },
        { word: "Welcome back", translation: "Bienvenido/a de nuevo" },
        { word: "How are you?", translation: "¿Cómo estás?" },
        { word: "How are you doing?", translation: "¿Cómo te va?" },
        { word: "How’s everything?", translation: "¿Cómo va todo?" },
        { word: "How’s it going?", translation: "¿Cómo te va?" },
        { word: "How have you been?", translation: "¿Cómo has estado?" },
        { word: "Long time no see", translation: "Cuánto tiempo sin verte" },
        { word: "What’s up?", translation: "¿Qué pasa?" },
        { word: "What’s new?", translation: "¿Qué hay de nuevo?" },
        { word: "What’s going on?", translation: "¿Qué sucede?" },
        { word: "Nice to see you", translation: "Me alegra verte" },
        { word: "Good to see you", translation: "Qué bueno verte" },
        { word: "Glad to see you", translation: "Me alegra verte" },
        { word: "Pleasure to meet you", translation: "Un placer conocerte" },
        { word: "Nice to meet you", translation: "Encantado de conocerte" },
        { word: "It’s a pleasure", translation: "Es un placer" },
        { word: "How do you do?", translation: "¿Cómo está usted?" },
        { word: "Greetings", translation: "Saludos" },
        { word: "Best regards", translation: "Saludos cordiales" },
        { word: "Cheers", translation: "Saludos/Adiós (informal)" },
        { word: "Yo", translation: "¡Ey! (muy informal)" },
        { word: "Hey there", translation: "Hola (informal)" },
        { word: "Hi there", translation: "Hola (amigable)" },
        { word: "Morning!", translation: "¡Buenos días!" },
        { word: "Afternoon!", translation: "¡Buenas tardes!" },
        { word: "Evening!", translation: "¡Buenas noches!" },
        { word: "Good to have you here", translation: "Qué bueno tenerte aquí" },
        { word: "Welcome home", translation: "Bienvenido a casa" },
        { word: "Welcome aboard", translation: "Bienvenido a bordo" },
        { word: "Welcome everyone", translation: "Bienvenidos todos" },
        { word: "Catch you later", translation: "Te veo luego" },
        { word: "Talk to you later", translation: "Hablamos luego" },
        { word: "Talk soon", translation: "Hablamos pronto" },
        { word: "Until next time", translation: "Hasta la próxima" },
        { word: "Until we meet again", translation: "Hasta que nos volvamos a ver" },
        { word: "See you in a bit", translation: "Nos vemos en un rato" },
        { word: "See you shortly", translation: "Nos vemos pronto" },
        { word: "See you tonight", translation: "Nos vemos esta noche" },
        { word: "Safe travels", translation: "Buen viaje" },
        { word: "Bon voyage", translation: "Feliz viaje" },
        { word: "Enjoy your trip", translation: "Disfruta tu viaje" },
        { word: "Enjoy your stay", translation: "Disfruta tu estancia" },
        { word: "Enjoy the rest of your day", translation: "Disfruta el resto de tu día" },
        { word: "Best wishes", translation: "Los mejores deseos" },
        { word: "All the best", translation: "Todo lo mejor" },
        { word: "Much love", translation: "Con mucho cariño" },
        { word: "Warm regards", translation: "Saludos cordiales" },
        { word: "Good luck", translation: "Buena suerte" },
        { word: "Fingers crossed", translation: "¡Que así sea! / Cruzo los dedos" },
        { word: "Take it easy", translation: "Tómatelo con calma" },
        { word: "Peace", translation: "Paz (despedida)" },
        { word: "Later", translation: "Nos vemos (informal)" },
        { word: "Later on", translation: "Hasta luego" },
        { word: "Bye", translation: "Adiós" },
        { word: "Goodbye", translation: "Adiós" },
        { word: "Bye bye", translation: "Chao" },
        { word: "See ya", translation: "Nos vemos (informal)" },
        { word: "Catch ya later", translation: "Nos vemos después (informal)" },
        { word: "So long", translation: "Hasta pronto" },
        { word: "Farewell", translation: "Despedida formal" },
        { word: "I’m off", translation: "Me voy" },
        { word: "Gotta go", translation: "Tengo que irme" },
        { word: "I’ll be back", translation: "Volveré" },
        { word: "See you at work", translation: "Nos vemos en el trabajo" },
        { word: "See you in class", translation: "Nos vemos en clase" },
        { word: "See you online", translation: "Nos vemos en línea" },
        { word: "See you at the party", translation: "Nos vemos en la fiesta" },
        { word: "See you at the meeting", translation: "Nos vemos en la reunión" },
        { word: "See you at church", translation: "Nos vemos en la iglesia" },
        { word: "See you next week", translation: "Nos vemos la próxima semana" },
        { word: "See you next month", translation: "Nos vemos el próximo mes" },
        { word: "See you next year", translation: "Nos vemos el próximo año" },
        { word: "Hello there", translation: "Hola" },
        { word: "Howdy", translation: "¡Hola! (estilo del oeste de EE.UU.)" },
        { word: "Sup?", translation: "¿Qué tal? (muy informal)" },
        { word: "Yo man!", translation: "¡Ey, amigo! (informal)" },
        { word: "Hey buddy", translation: "Hola, amigo" },
        { word: "Hey bro", translation: "Hola, hermano (informal)" },
        { word: "Hey sis", translation: "Hola, hermana (informal)" },
        { word: "Hey guys", translation: "Hola chicos" },
        { word: "Hey everyone", translation: "Hola a todos" },
        { word: "Hey folks", translation: "Hola gente" },
        { word: "Hey mate", translation: "Hola colega (británico/australiano)" }
    ],
    colors: [
        { word: "Red", translation: "Rojo" },
        { word: "Blue", translation: "Azul" },
        { word: "Green", translation: "Verde" },
        { word: "Yellow", translation: "Amarillo" },
        { word: "Black", translation: "Negro" },
        { word: "White", translation: "Blanco" },
        { word: "Gray", translation: "Gris" },
        { word: "Orange", translation: "Naranja" },
        { word: "Purple", translation: "Morado/Violeta" },
        { word: "Pink", translation: "Rosado" },
        { word: "Brown", translation: "Marrón/Café" },
        { word: "Beige", translation: "Beige" },
        { word: "Gold", translation: "Dorado" },
        { word: "Silver", translation: "Plateado" },
        { word: "Turquoise", translation: "Turquesa" },
        { word: "Navy", translation: "Azul marino" }
    ],
    animals: [
        { word: "Dog", translation: "Perro" },
        { word: "Cat", translation: "Gato" },
        { word: "Bird", translation: "Pájaro" },
        { word: "Fish", translation: "Pez" },
        { word: "Cow", translation: "Vaca" },
        { word: "Horse", translation: "Caballo" },
        { word: "Chicken", translation: "Gallina" },
        { word: "Pig", translation: "Cerdo" },
        { word: "Sheep", translation: "Oveja" },
        { word: "Duck", translation: "Pato" },
        { word: "Goat", translation: "Cabra" },
        { word: "Mouse", translation: "Ratón" },
        { word: "Rabbit", translation: "Conejo" },
        { word: "Lion", translation: "León" },
        { word: "Tiger", translation: "Tigre" },
        { word: "Elephant", translation: "Elefante" },
        { word: "Bear", translation: "Oso" },
        { word: "Monkey", translation: "Mono" },
        { word: "Wolf", translation: "Lobo" },
        { word: "Snake", translation: "Serpiente" }
    ]
};

const cards = categories.saludos;